name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - tests

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "17"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3    
      
      - name: Install Node.js dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npx jest

      - name: Install Docker
        run: |
          if ! [ -x "$(command -v docker)" ]; then
            echo "Installing Docker..."
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            sudo usermod -aG docker $USER
          else
            echo "Docker is already installed"
          fi

      - name: Set permissions for Docker socket
        run: |
          sudo chmod +666 /var/run/docker.sock

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-app:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:latest
      

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo mv minikube-linux-amd64 /usr/local/bin/minikube
          sudo chmod +x /usr/local/bin/minikube

      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.23.0/bin/linux/amd64/kubectl
          sudo mv kubectl /usr/local/bin/kubectl
          sudo chmod +x /usr/local/bin/kubectl

      - name: Start Minikube
        run: |
          minikube start --driver=docker

      - name: Set up kubectl
        run: |
          minikube kubectl -- get pods
          sudo cp /usr/local/bin/kubectl /usr/bin/kubectl
          kubectl version --client

      - name: Deploy to Minikube
        run: |
          kubectl apply -f deployment.yaml && sleep 20

      - name: Verify Deployment
        run: |
          kubectl get deployments
          kubectl get pods

      - name: Apply Service File to Minikube
        run: |
          kubectl apply -f ./service.yaml

      - name: Expose the Service Using Minikube Tunnel
        run: |
          sudo minikube tunnel &

      - name: Expose Service and Get URL
        run: |
          minikube service node-app-service --url

      - name: Port-forward the service to localhost in the background
        run: |
          kubectl port-forward --address 0.0.0.0 svc/node-app-service 30080:80 &
